### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by TT-mouse** [Yang-Shiyuan/ResInpainting#3]
作者你好，我在使用你提供的预训练模型在巴黎数据集进行训练的时候，会报错：
D:\Anaconda\envs\CTSDG\lib\site-packages\torch\nn\functional.py:3635: UserWarning: Default upsampling behavior when mode=bicubic is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)
Traceback (most recent call last):
  File "E:/our code/ResInpainting-main-our/train.py", line 2, in <module>
    main(mode=1)
  File "E:\our code\ResInpainting-main-our\main.py", line 49, in main
    model.train()
  File "E:\our code\ResInpainting-main-our\src\ResInpainting.py", line 163, in train
    outputs2, gen2_loss, dis2_loss, logs2 = self.inpaint_model2.process(images2, outputs1_merged, masks2)
  File "E:\our code\ResInpainting-main-our\src\models.py", line 206, in process
    outputs = self(images_gt, images_in, masks)  # 喂给generator
  File "D:\Anaconda\envs\CTSDG\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\our code\ResInpainting-main-our\src\models.py", line 251, in forward
    images_in = (F.interpolate(images_in, scale_factor=2, mode='bicubic') * masks) + (images_gt * (1 - masks))  # 低分辨率图 上采样后 和高分辨率gt融合
RuntimeError: The size of tensor a (256) must match the size of tensor b (936) at non-singleton dimension 3。
请问如何解决？

**Comment by cats-food** [comment]
第一个警告，插值函数多传一个align_corners=True，也可以将mode从bicubic 改为bilinear

至于RuntimeError，看样子应该是图片相乘的时候尺寸不匹配，可以在这一行加一个断点，查看masks，images_gt的尺寸是不是256*256，images_in的尺寸是不是128*128。

**Comment by TT-mouse** [comment]
> 



> 第一个警告，插值函数多传一个align_corners=True，也可以将mode从bicubic 改为bilinear
> 
> 至于RuntimeError，看样子应该是图片相乘的时候尺寸不匹配，可以在这一行加一个断点，查看masks，images_gt的尺寸是不是256_256，images_in的尺寸是不是128_128。

我打断点调试时显示masks和images_gt的尺寸均为537_936的原图尺寸，image_in是128_128，应该是masks和images_gt的大小没有处理。请问您在输入原图时遇到过这个问题吗？

**Comment by cats-food** [comment]
537_936尺寸不对，你需要把图片预处理成成256x256的才能送进网络
